AWSTemplateFormatVersion: '2010-09-09'
Description: Blog Post - Hidratating ElasticSearch and Kibana using AWS Batch and Logstash.

Parameters:
  Tag:
    Description: Name used to identified  values. Defaults to
    Type: String
    Default: BLOG
    MaxLength: 16
    MinLength: 4

Resources:
  ECRData:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "blog-data"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ":"
                  - - 'arn:aws:iam:'
                    - Ref: AWS::AccountId
                    - 'root'
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
  ECRProcess:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: "blog-process"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                Fn::Join:
                  - ":"
                  - - 'arn:aws:iam:'
                    - Ref: AWS::AccountId
                    - 'root'
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"

Outputs:
  ECRData:
    Description: ECRData
    Value:
      Ref: ECRData
    Export:
      Name: !Sub '${Tag}-ECRData'
  ECRProcess:
    Description: ECRProcess
    Value:
      Ref: ECRProcess
    Export:
      Name: !Sub '${Tag}-ECRProcess'
