AWSTemplateFormatVersion: '2010-09-09'
Description: Blog Post - Hidratating ElasticSearch and Kibana using AWS Batch and Logstash.

Parameters:
  Tag:
    Description: Name used to identified  values.
    Type: String
    Default: BLOG
    MaxLength: 16
    MinLength: 4

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: BucketOwnerFullControl
      BucketName:
        Fn::Join:
          - "-"
          - - 'blog'
            - Ref: AWS::Region
            - Ref: AWS::AccountId
      Tags:
      - Key: Name
        Value: !Sub '${Tag}'

Outputs:
  S3Bucket:
    Description: 'S3Bucket'
    Value: !Ref S3Bucket
    Export:
      Name: !Sub '${Tag}-S3Bucket'
